import { ANYTHING_V3_URL, OPEN_JOURNEY_URL } from './runpod.constants';
export const MODEL_TYPES = {

  ANYTHING_V3: 'ANYTHING_V3',
  OPEN_JOURNEY: 'OPEN_JOURNEY',
};

export const MODEL_DESCRIPTIONS = {
  ANIME: 'Anime',
  REALISTIC: 'Realistic',
};

export const DESCRIPTION_TO_MODEL = {
  [MODEL_DESCRIPTIONS.ANIME]: ANYTHING_V3_URL,
  [MODEL_DESCRIPTIONS.REALISTIC]: OPEN_JOURNEY_URL,
};
