apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: greetings
          image: us-west2-docker.pkg.dev/elegant-tangent-374007/card-couture/greetings
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URL
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
