import Head from "next/head";
import NuxtLink from "next/link";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import * as Avatar from "@radix-ui/react-avatar";
import {
  Plus,
  Image as ImageIcon,
  Edit3,
  LayoutTemplate,
  User,
  LogOut
} from "lucide-react";
import { GreetingCardSVG } from "./GreetingCardSVG";
import { FancyGreetingCard } from "./FancyGreetingCard";

export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="fixed h-screen bg-white shadow-sm w-64">
        <div className="h-full overflow-y-auto scrollbars">
          <div className="mh-18 text-center py-5">
            <a href="#" className="relative">
              <h2 className="flex text-2xl font-semibold text-gray-200 px-4 max-h-9">
                <GreetingCardSVG />
                <span className="text-gray-700 dark:text-gray-200">
                  Card Couture
                </span>
              </h2>
              <h2 className="text-3xl font-semibold mx-auto logo-compact hidden">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="inline-block w-7 h-7 -mt-1"
                  viewBox="0 0 300.000000 300.000000"
                >
                  <g
                    transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)"
                    fill="currentColor"
                    stroke="none"
                  >
                    <path
                      className="text-pink-500"
                      d="M1225 2825 c-546 -115 -959 -534 -1065 -1080 -28 -147 -28 -373 0
                  -520 81 -419 350 -774 728 -964 115 -58 120 -58 65 3 -27 29 -65 84 -85 122
                  -68 131 -90 236 -89 428 0 229 44 470 167 923 41 149 74 275 74 278 0 4 -102
                  5 -227 3 -198 -4 -236 -7 -290 -25 -35 -12 -63 -18 -63 -14 0 4 22 43 49 87
                  58 93 123 157 177 175 22 6 124 14 234 16 l195 5 33 112 c91 305 200 431 405
                  465 43 7 31 9 -73 9 -94 1 -152 -5 -235 -23z"
                    ></path>
                    <path
                      className="text-indigo-500"
                      d="M1695 2763 c-48 -77 -122 -231 -179 -375 -25 -65 -46 -120 -46 -123
                  0 -7 995 -6 1069 1 34 4 61 12 61 18 0 6 -30 46 -65 88 -170 201 -426 361
                  -687 428 -110 29 -111 28 -153 -37z"
                    ></path>
                    <path
                      className="text-indigo-500"
                      d="M2660 2104 c-33 -36 -54 -47 -120 -67 -21 -6 -256 -12 -595 -16
                  l-560 -6 -51 -180 c-62 -215 -116 -445 -144 -608 -74 -435 -37 -655 124 -740
                  62 -32 189 -30 274 5 174 72 337 212 410 353 l20 40 24 -50 c32 -70 32 -162
                  -1 -229 -48 -97 -216 -250 -383 -347 -86 -51 -170 -85 -261 -109 l-69 -17 94
                  -6 c469 -33 947 205 1214 605 229 342 291 790 163 1173 -24 70 -76 192 -94
                  217 -10 16 -14 14 -45 -18z"
                    ></path>
                  </g>
                </svg>
              </h2>
            </a>
          </div>

          <ul className="w-full flex flex-col font-medium pl-1.5 pr-1.5">
            <li className="relative">
              <NuxtLink
                href="/"
                className="block py-2.5 px-6 hover:text-indigo-500 text-indigo-500 flex align-center"
              >
                <Plus className="inline-block h-4 w-4 mr-2 ml-2 bi bi-card-list" />
                <span>Create New</span>
              </NuxtLink>
            </li>

            <div className="py-2">
              <div
                className="bg-gray-300"
                style={{ margin: "0 1.5rem", height: "1px" }}
              ></div>
            </div>

            <li className="relative">
              <NuxtLink
                href="/cards"
                className="block py-2.5 px-6 hover:text-indigo-500 flex align-center"
              >
                <FancyGreetingCard />
                <span>My Cards</span>
              </NuxtLink>
            </li>

            <li className="relative">
              <NuxtLink
                href="/greetings"
                className="block py-2.5 px-6 hover:text-indigo-500 flex align-center"
              >
                <Edit3 className="inline-block h-4 w-4 mr-2 ml-2 bi bi-card-list" />
                <span>My Greetings</span>
              </NuxtLink>
            </li>

            <li className="relative">
              <NuxtLink
                href="/images"
                className="block py-2.5 px-6 hover:text-indigo-500 flex align-center"
              >
                <ImageIcon className="inline-block h-4 w-4 mr-2 ml-2 bi bi-card-list" />
                <span>My Images</span>
              </NuxtLink>
            </li>

            <li className="relative">
              <NuxtLink
                href="/templates"
                className="block py-2.5 px-6 hover:text-indigo-500 flex align-center"
              >
                <LayoutTemplate className="inline-block h-4 w-4 mr-2 ml-2 bi bi-card-list" />
                <span>Templates</span>
              </NuxtLink>
            </li>
          </ul>

          <div className="px-4 box-banner">
            <div className="my-8 p-4 text-center bg-gray-300 dark:bg-gray-700 bg-opacity-50 rounded-lg">
              <h4 className="font-bold inline-block mb-2">Model Status</h4>
              <div className="mb-3 text-sm">Your model is ready to view!</div>

              <div className="grid">
                <a
                  href="#"
                  className="py-2 px-4 inline-block text-center mb-3 rounded leading-5 text-gray-100 bg-pink-500 border border-pink-500 hover:text-white hover:bg-pink-600 hover:ring-0 hover:border-pink-600 focus:bg-pink-600 focus:border-pink-600 focus:outline-none focus:ring-0"
                  target="_blank"
                >
                  View
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <main className="bg-gray-100 h-screen" style={{ marginLeft: "16rem" }}>
        <nav className="z-50 sticky flex flex-row flex-nowrap items-center justify-end mt-0 py-2 left-0 md:left-64 right-0 right-0 md:right-64 left-0 px-6 bg-white shadow-sm">
          <DropdownMenu.Root>
            <DropdownMenu.Trigger>
              <button>
                <Avatar.Root className="AvatarRoot">
                  <Avatar.Image className="AvatarImage" src="" alt="MT" />
                  <Avatar.Fallback className="AvatarFallback" delayMs={600}>
                    MT
                  </Avatar.Fallback>
                </Avatar.Root>
              </button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content
                className="DropdownMenuContent"
                sideOffset={5}
              >
                <DropdownMenu.Item className="DropdownMenuItem">
                  Matt Taggart
                </DropdownMenu.Item>
                <DropdownMenu.Separator className="DropdownMenuSeparator" />
                <DropdownMenu.Item className="DropdownMenuItem">
                  <NuxtLink
                    href="/profile"
                    className="block hover:text-indigo-500 flex align-center"
                  >
                    <User className="inline-block h-4 w-4 mr-1" />
                    <span className="p-1">My Profile</span>
                  </NuxtLink>
                </DropdownMenu.Item>
                <DropdownMenu.Item className="DropdownMenuItem">
                  <NuxtLink
                    href="/cards"
                    className="block hover:text-indigo-500"
                  >

                    <LogOut className="inline-block h-4 w-4 mr-1" />
                    <span className="p-1">Logout</span>
                  </NuxtLink>
                </DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>{" "}
        </nav>
        <div className="p-4">{children}</div>
      </main>
    </>
  );
}
